### ISSUE TITLE
Conflicting names with version 1.9.0

### ISSUE THREAD

**Issue by hexadecy** [Gainsight/px-react-native-sdk#12]
In our _package.json_
```json
"react-native-gainsight-px": "https://github.com/Gainsight/px-react-native-sdk.git#d7467353910e5dad13b11652bcb8e4d127129ede",
```

In our _Podfile_, I have added this line:
```
pod 'PXKit', :git => 'https://github.com/Gainsight/px-ios.git', tag: '1.9.0'
```

When I do `pod install`
```Shell
[!] The 'Pods-App-Mobile' target has frameworks with conflicting names: pxkit.xcframework.
```

What's wrong?

**Comment by gs-apentapati** [comment]
Please do not use or remove this line `'PXKit', :git => 'https://github.com/Gainsight/px-ios.git', tag: '1.9.0'` from project pod spec

**Comment by hexadecy** [comment]
@gs-apentapati What do you mean by that? 

There is no source there:
https://github.com/Gainsight/px-react-native-sdk/blob/d7467353910e5dad13b11652bcb8e4d127129ede/RNGainsightPx.podspec#L8

Right now, I have it working with 1.7.3.
` pod 'PXKit', :git => 'https://github.com/Gainsight/px-ios.git', tag: '1.7.3'`

Please include the source in _RNGainsightPx.podspec_

Like that:
`s.source = { :git => "https://github.com/Gainsight/px-ios.git", :tag => "#{s.version}" }`

**Comment by gs-apentapati** [comment]
should remove `pod 'PXKit', :git => 'https://github.com/Gainsight/px-ios.git', tag: '1.9.0'` from pod file
> Remove Node modules
> Remove lock file
> Remove ios/Pods
> Remove ios/Pod lock file
> Remove workspace file

do `npm install`, and `pod install` in iOS directory

**Comment by hexadecy** [comment]
Ok it works, thank you.
