### ISSUE TITLE
Confusion with Android Setup Documentation

### ISSUE THREAD

**Issue by woodrufs** [Gainsight/px-react-native-sdk#14]
We're trying to configure Gainsight px with our react native application, but we are running into some confusion. We're trying to focus on Android. We're not getting any build errors and our methods for some screen event logging are being hit, but we aren't seeing anything in Gainsight.

Reviewing the documentation, one part of confusion is when it tells us to add this to the build.gradle:

```
allprojects {
...
    repositories {
...
        flatDir {
            dirs new File(rootProject.projectDir, '../node_modules/react-native-gainsight-px/android/libs')
        }
    }
}      

```

We aren't seeing a folder named libs in the android folder, and we are wondering if this is why we aren't seeing any results. I was hoping your team could comment on this and let us know if `/android/libs` is actually the right location or if this may need updating.

Thank you!

**Comment by woodrufs** [comment]
This ended up not being an issue. We are new to Gainsight and made a rookie mistake. We saw the user in Gainsight we expected the data to be tracked against, but the mobile events were not appearing. Our web app was initializing the user via their username in our domain, and then our mobile app was initializing them with their email. That made it track against two different users. After realizing a second user was created and navigating to it, we noticed all our data was there.

Sorry for creating this!

**Comment by bobonthenet** [comment]
The documentation says there should be a /node_modules/react-native-gainsight-px/android/libs folder but in the 1.9.0 apk that folder does not exist. This results in the in app product mapper not working. There might be additional reasons that the 1.9.0 apk does not work but this is the most obvious that I was able to identify. I was only able to complete the implementation by getting a copy of the 1.4.0 apk from a colleague that had been sent that version directly through email for an earlier react native implementation. That libs folder should exist but doesn't. This is still an issue.
