### ISSUE TITLE
Publish a version on npmjs or a tag on github

### ISSUE THREAD

**Issue by hexadecy** [Gainsight/px-react-native-sdk#4]
Can you please publish the latest version on npm.
Currently, the version on npmjs is 1.5.2
https://www.npmjs.com/package/react-native-gainsight-px

**Comment by bobonthenet** [comment]
My organization also really needs the current release published to npm. We do not wish to use github as the dependency because it is not versioned. This is a security concern for us because we are unable to specify a specific version for our CI/CD pipelines.

**Comment by hexadecy** [comment]
Good, we now have it on npmjs:
[@gainsight-px/react-native-gainsight-px](https://www.npmjs.com/package/@gainsight-px/react-native-gainsight-px)
